### ISSUE TITLE
Python Script not accepting

### ISSUE THREAD

**Issue by warebear** [emmetio/npp#14]
NPP version: 6.9
PythonScript version: 1.0.6.0
EmmetNPP version 1.0.0

When I attempt to run it I get the following popups:
Unknown Exception

Then I get
Python Script Plugin did not accept the script

I am simply doing td*5  so I should get 5 TD tags

**Comment by eight04** [comment]
Try installing the latest version:
https://sourceforge.net/projects/npppythonscript/files/

**Comment by warebear** [comment]
Installed 1.0.8 and now working.  Thanks!  Apparently Plugin Manager installs the 1.0.6 version.
